server:
  port: 8080

spring:
  application:
    name: MensajeriaChat

    datasource:
      url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:chat}
      username: ${DB_USER:postgres}
      password: ${DB_PASS:postgres}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

  jwt:
    secret: ${JWT_SECRET:changeit}
    expiration-ms: ${JWT_EXP:86400000} # 1 day

  spring:
    main:
      allow-bean-definition-overriding: true